### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by knghtbrd** [YeOldeInn/agins-archive#1]
Here's the list of things that need to be done for the Agin's Inn archive

- [x] Get the HTML files into git (stage 1)
- [x] Add the images (stage 2)
- [ ] Port to HTML 5 (stage 3)
   This will go slowly at first and then pick up as more and more gets done to it
   - [ ] lotrmenu.htm
   - [ ] moriagauntletpage.htm
   - [ ] equip.htm
   - [ ] hqboardtiles.htm
   - [ ] balinstombpage.htm
   - [ ] faqtiles.htm
   - [ ] workingstiff/brandypix.htm
   - [ ] gamemaster/versions.htm
   - [ ] gamemaster/whatsnew.htm
   - [ ] gamemaster/coming.htm
   - [ ] gamemaster/screenshots.htm
   - [ ] gamemaster/about.htm
   - [ ] gamemaster/quests.htm
   - [ ] gamemaster/inst_editing.htm
   - [ ] gamemaster/inst_pbem.htm
   - [ ] gamemaster/inst_playing.htm
   - [ ] gamemaster/quest_ratings.htm
   - [ ] gamemaster/inst_objects.htm
   - [ ] gamemaster/inst_ai.htm
   - [ ] pits.htm
   - [ ] rohanbanpage.htm
   - [ ] heroes/halflingthief.html
   - [ ] heroes/elfarcher.html
   - [ ] heroes/beastmaster.html
   - [ ] heroes/elf.html
   - [ ] heroes/paladin.html
   - [ ] heroes/panther.html
   - [ ] heroes/cleric.html
   - [ ] heroes/wizard.html
   - [ ] heroes/ranger.html
   - [ ] heroes/goblinslave.html
   - [ ] heroes/amazon.html
   - [ ] heroes/executioner.html
   - [ ] heroes/dwarf.html
   - [ ] heroes/slayer.html
   - [ ] heroes/witchhunter.html
   - [ ] heroes/mystic.html
   - [ ] heroes/barbarian.html
   - [ ] heroes/templar.html
   - [ ] heroes/wardancer.html
   - [ ] heroes/monk.html
   - [ ] heroes/swordmaster.html
   - [ ] heroes/cleric2.html
   - [ ] heroes/steel.html
   - [ ] heroes/engineer.html
   - [ ] heroes/shapeshifter.html
   - [ ] heroes/ogre.html
   - [ ] tilesfuture.html
   - [ ] tilesdungeon.html
   - [ ] monsters.html
   - [ ] tiles.html
   - [ ] contest.html
   - [ ] unarmed.html
   - [ ] castles.html
   - [ ] tilessea.html
   - [ ] testimonials.html
   - [ ] tilescave.html
   - [ ] finding.html
   - [ ] tilesoutdoors2.html
   - [ ] minisrons.html
   - [ ] tilesmichael.html
   - [ ] furniture.html
   - [ ] lava1.html
   - [ ] rules.html
   - [x] new.html
   - [ ] paperminis.html
   - [ ] fate.html
   - [ ] gladiatorquest.html
   - [ ] printing.html
   - [ ] tilesice.html
   - [ ] maze.html
   - [ ] philosophy.html
   - [ ] tilesdungeon2.html
   - [ ] tilesmine.html
   - [ ] randomquest.html
   - [ ] runesmith.html
   - [ ] tilesaccessories.html
   - [ ] index.html
   - [ ] henchmen.html
   - [ ] games/ds.html
   - [ ] games/ahq.html
   - [ ] games/dw.html
   - [ ] move.html
   - [ ] minisdaves.html
   - [ ] twoweapons.html
   - [ ] hqcards.html
   - [ ] minischristines.html
   - [ ] spells.html
   - [ ] tilesron.html
   - [ ] abench.html
   - [ ] tilestoco.html
   - [ ] weaponpix.html
   - [ ] minis.html
   - [ ] tilesdany.html
   - [ ] faq.html
   - [ ] heroes.html
   - [ ] inventory.html
   - [ ] monsters/goblinshaman.html
   - [ ] monsters/smallgoblin.html
   - [ ] monsters/fireelemental.html
   - [ ] monsters/pharaoh.html
   - [ ] monsters/elf.html
   - [ ] monsters/dragon.html
   - [ ] monsters/orcarcher.html
   - [ ] monsters/troll2.html
   - [ ] monsters/orcwarchief.html
   - [ ] monsters/necromancer.html
   - [ ] monsters/minotaur.html
   - [ ] monsters/wizard.html
   - [ ] monsters/doomguard.html
   - [ ] monsters/skaven.html
   - [ ] monsters/scarab.html
   - [ ] monsters/rat.html
   - [ ] monsters/chaoschampion.html
   - [ ] monsters/orcchampion.html
   - [ ] monsters/chaoslord.html
   - [ ] monsters/wanderer.html
   - [ ] monsters/goblinslave.html
   - [ ] monsters/orcdaemon.html
   - [ ] monsters/morcarvonzargon.html
   - [ ] monsters/liche.html
   - [ ] monsters/balrog.html
   - [ ] monsters/bat.html
   - [ ] monsters/dwarf.html
   - [ ] monsters/spider.html
   - [ ] monsters/hellhound.html
   - [ ] monsters/wolf.html
   - [ ] monsters/orcbigun.html
   - [ ] monsters/undeadchampion.html
   - [ ] monsters/fearsomeskeleton.html
   - [ ] monsters/troll.html
   - [ ] monsters/barbarian.html
   - [ ] monsters/swampdruid.html
   - [ ] monsters/djinn.html
   - [ ] monsters/terriblegargoyle.html
   - [ ] monsters/goblinspearman.html
   - [ ] monsters/fimir.html
   - [ ] monsters/skeletalwarrior.html
   - [ ] monsters/invulnerablemummy.html
   - [ ] monsters/ghoul.html
   - [ ] monsters/bosstroll.html
   - [ ] monsters/elementals.html
   - [ ] monsters/goblinscout.html
   - [ ] monsters/diseasedzombie.html
   - [ ] monsters/goblinarcher.html
   - [ ] monsters/spiders.html
   - [ ] monsters/shapeshifter.html
   - [ ] monsters/manscorpion.html
   - [ ] advance.html
   - [ ] randomquest/randomquestrules.html
   - [ ] randomquest/cavetiles.html
   - [ ] news.html
   - [ ] contests/contestdecember2001.html
   - [ ] contests/contestjune2001.html
   - [ ] alchemist.html
   - [ ] gladiatorquest/gladiatorquestrules.html
   - [ ] tilesoutdoors.html
   - [ ] minisazraels.html
   - [ ] links.html
   - [ ] hqboardtiles2.html
   - [ ] quests.html (in progress) 
   - [ ] tilesken.html
   - [ ] workingstiff/classic.html
   - [ ] workingstiff/maze.html
   - [ ] workingstiff/largetiles.html
   - [ ] workingstiff/deluxesci.html
   - [ ] workingstiff/db.html
   - [ ] gamemaster/index.html
   - [ ] icons.html
   - [ ] games.html
   - [ ] royalpalace.html
   - [ ] armory.html
   - [ ] tilesdewayne.html
   - [ ] tilesinn.html
- [ ] Move files aaround and create 301s (stage 4)
- [x] Remove the php wrapper thingy that makes it so you can't see internal pages of the archive on YeOldeInn
      (Trust me that made sense.)
- [ ] Resolve "orphan" files (see issue #3)
      - [ ] HTML files
      - [ ] Images
      - [ ] Any other resources left when those are done
- [ ] Test all links at the [github pages link](https://yeoldeinn.github.io/agins-archive/) before deploying it to the Inn
- [ ] Set this repo up to be live at YeOldeInn
- [ ] Make the site completely self-contained so that it doesn't depend on Ye Olde Inn anymore (trivial)
- [x] Create some standard machine-searchable "broken link" markup
   ``` html
   <span class="nolink" title="info about the non-link">what user sees</span>
   ```
- [ ] Fix any broken links that have fixes
- [ ] Remove the email addresses that are all over the site. Safer contact method if we have one maybe?
      This one's in progress, there's just a lot of them.
- [x] Write a license file for this content. Not because we need one, but because in 2022 we know it should exist.
      Done pending approval from everyone who needs to give it.

What else ought to be done? Comment below. How much time/effort do we want to spend on the historical archive? I want the site's broken links resolved at least.

**Comment by knghtbrd** [comment]
Since we don't have Dewayne Agin to 👍 or 👎 any license (he kinda left it all in drathe's hands) and so many other contributors to that site are now basically just gone now, it needs to be something respectful to all of them and what I think their clear intention was.

It's clear from the eBay dude selling $45 decks of homebrew cards off the Inn that we can't actually stop bad people from doing bad things, but a basic "give credit and don't be a dick or we're all going to mock and ridicule you" sort of license is all we can realistically hope for. It's certainly all we've generally been able to enforce.

Sorely tempted:

```
This content was created by fans of HeroQuest. It is made for and occasionally partially derived from
HeroQuest in ways we believe were intended and are permitted by HeroQuest's owner. Use what you
find in whatever way seems like fun. Giving credit where due is appreciated, and please don't be like
that douche selling $45 decks of cards he downloaded off YeOldeInn on eBay.
```

I've written actual licenses before. They're rarely that much fun to read. 🤣

**Comment by DaedalusInn** [comment]
Love that license!

**Comment by knghtbrd** [comment]
LOL, I wrote something down a little more "proper" I was going to post over at the Inn for feedback, but I figured for the time being it can wait, but I wrote it before a conversation I had over the weekend that might ever so slightly change what it probably ought to say. It should be fine to leave it as it is for the moment since all that's here now are a bunch of HTML files and a few website graphics. I dunno if I want to put the various downloads into git or not.

I have at least that long before I really ought to come up with something and I think I really should clean up some HTML first. I didn't plan on it, but fixing the thing to display on 1080p much less 4k screens makes it kind of important.

**Comment by knghtbrd** [comment]
Edited to reflect the sub-steps of the first goal. The HTML files are in git. The images are … lemme do some figuring. This is gonna look like line noise…

```
tjcarter@aki:~/YeOldeInn/agins-archive$ grep -l '^<!-- ##' $(find -name \*.htm\*) | wc -l
93
tjcarter@aki:~/YeOldeInn/agins-archive$ grep -L '^<!-- ##' $(find -name \*.htm\*) | wc -l
115
```

I've been through 93 files, and I have 115 left to look at to add images. Many of these don't have any images and only need one line added to them (a comment line in the HTML code I'm adding as I go). Those are quick. The others take a little longer. More figuring (skipped), 66 of the 115 have images that may need to be added to the archive. That means … yup, 49 … 49 do not.

If you don't want an explanation for that crazy unixy grep stuff above, you can skip the rest of this comment. It's not necessary to help with any of this stuff, but might be of interest if you've been learning UNIX command line stuff for Linux or Mac, or WSL usage. I've just gotten into explanation mode with the se things, so may as well continue the trend.

Remember how in math class you would do stuff in () first? In this case, we do what's in $() first. That's "find -name \*.htm\*". That spits out a list of all HTML files in the tree. Save one that should be in the tree and isn't because I know it's a duplicate already and it's got spaces in the filename. Those add to the complexity of unixy stuff like the above, so since I know I will be deleting that file anyway, I've not added it to the repository. I'll compare it against its near identical dupe … sooner or later.

Okay so now we have a list of files. Well, the $() bit takes that list (normally one per line) and glues them all together as a list of files on one line. Then there's the grep part. Let's go with the first one, `grep -l '^<!-- ##'`. I said I'm adding a comment to the end of files as I go. Here's one:

```
<!-- ##2## -->
```

To make a comment in a web page, you start it with `<!--` and finish it with `-->`. And at this point, I have to of those: ##2## and ##ORPHAN##. I used those because they're not going to appear anywhere else in any of the files if I don't put it there. I can search for any file that's been through stage 2 with `grep -l '##2##'`. The -l stands for list, as in list files that match. So I'm looking for any file above that matches `'^<!-- ##'` which means any file containing the start of an HTML comment followed by a space and two number signs. If you hadn't guessed, in the second line, I use -L which says give me a list of files that DON'T have that in them.

If you know that you can use \`\` for "subshell", `$()` is a so-called "bashism" that does the same thing. Except it can be nested! Which means if I want to tale a list of files that don't have my comment indicating I've "processed" them and search for images within, yup, I can $() and precede it with `grep -l 'src='`. or -L if I want the list that don't. This is all 1970s tech, chaining commands together to get what you want. On Windows, PowerShell does the same kind of things, it just does it with "objects" rather than text, and Microsoft makes you type a lot more verbiage because PowerShell was designed by a frickin' committee of pretentious intellectuals who wanted to "design the perfect system" on multi-gigahertz systems with boat loads of RAM as opposed to code monkeys who just wanted to get shit done on machines that might have 32. Kilobytes, not gigabytes.

**Comment by knghtbrd** [comment]
Hey @DaedalusInn, how's this?

> HeroQuest, Avalon Hill, all associated Trademarks, and the Copyright to HeroQuest are owned by Hasbro, Inc. This site is not intended to challenge Hasbro's rights or commercial interests.
>
> Agin's Inn is the work of fans who provide their creations to use, improve, and share freely. Anything commercial requires their permission. And maybe Hasbro's. Good luck with that!

I think it covers what needs covering.

**Comment by DaedalusInn** [comment]
The  copyright disclaimer
 looks good to me!
